### ISSUE TITLE
Image display shifts when switching image files

### ISSUE THREAD

**Issue by Adamtk22** [alabamagan/NIfTI-gridview#5]
Image display shifts by itself when switching image files

Replication steps
1. Load image
2. Change display size or display center position
3. Load another image

First image
![Capture](https://user-images.githubusercontent.com/105408111/178684133-a6810679-c6af-41eb-8e39-fcc43977452c.PNG)

Second image
![Capture2](https://user-images.githubusercontent.com/105408111/178684245-66c93673-add2-4a32-829c-c8f5bbcd0b5c.PNG)

**Comment by alabamagan** [comment]
Does moving the bars reset the view to correct parameters?

**Comment by Adamtk22** [comment]
This issue can be fixed by adding sliderReleased signals to the horizontal sliders

see 
https://github.com/Adamtk22/NIfTI-gridview-dev/commit/23774dbf1a25e2ad87aab6d0f05bdd54616594a3

**Comment by alabamagan** [comment]
Could you make a PR for this fix?

**Comment by Adamtk22** [comment]
https://github.com/alabamagan/NIfTI-gridview/pull/3

this pull request should have the commit
